### ISSUE TITLE
Expand error handling specification

### ISSUE THREAD

**Issue by perj** [wamp-proto/wamp-proto#108] opened 2014-11-12 11:27 UTC
I might've missed it, but error handling seems very limited in the specification.
What should a router do if client sends:
- Before a session is established:
  - Invalid message (can't be json decoded)
  - Empty message (empty list for json)
  - Any other message than HELLO
  - A short message (HELLO or not)
  - An invalid parameter in a message (HELLO or not). E.g. realm is not a string, request id not an int.
  - HELLO with no roles.
- Once a session is established:
  - Invalid message (can't be json decoded)
  - Empty message (empty list for json)
  - HELLO or WELCOME
  - An unknown message code
  - A short message
  - An invalid parameter in a message. E.g. realm is not a string, request id not an int.

If ABORT is ever supposed to be sent after a session is established that part needs to be clarified as well, since currently it clearly says ABORT is only sent before a session is established.

**Comment by angiolep** [comment] 2016-09-21 21:05
I also had the same feeling and filed issue #255 which looks similar to this.

**Comment by KSDaemon** [comment] 2018-02-27 17:58
Well... I've just looked into my implementations, how i process this situations:
* On the ROUTER SIDE:
   * Receiving HELLO after session is established → router closes connection (GOODBYE, "wamp.error.system_shutdown")
   * Receiving AUTHENTICATE after session is established → same as HELLO
   * Receiving ANY pubsub/rpc messages BEFORE session is established → router closes connection (GOODBYE, "wamp.error.system_shutdown")
   * Receiving unknown message code → simply ignore
   * If message can not be encoded/decoded → serializer throws error, which means, i suppose connection will be aborted.
* On the CLIENT SIDE:
   * Receiving unknown message code → simply ignore
   * If message can not be encoded/decoded → serializer throws error, which means, i suppose connection will be aborted.

So in general, i do not try to prevent all possible errors, such as missing required parameters. This is a implementation task to prevent sending incorrect messages.

**Comment by oberstet** [comment] 2018-03-02 19:14
> This is a implementation task to prevent sending incorrect messages.

Sure, fully agreed! Crossbar.io (in fact AutobahnPython) has code that is supposed to only emit valid WAMP, but _additionally_ will bail out immediately on a protocol error from the peer. I guess I am following a paranoid-by-default or never trust code or bytes coming over network approach for security reasons. And continuing talking to a broken peer can expose further side conditions, as then the other side (eg Crossbar) needs a bigger state space etc - "the peer should fix its stuffs" if its severly broken is my view;)

**Comment by oberstet** [comment] 2018-03-02 20:24
However, what we can do of course is to define defaults for missing parameters, or we could define router options to relax the behavior in response to a broken (or at least somewhat broken) peer ,, but there are security implications here, so we should really look at the whole picture here IMO ...

**Comment by oberstet** [comment] 2018-03-03 19:38
Another approach that could be realized without changing the state machines in the protocol implementations: when the message could be read at the transport level (eg the WebSocket message framing was valid) and could be deserialized, a CALL with sth invalid is answered with CALL_ERROR, and a PUBLISH that is acknowledged is answered with an ERROR. And that behavior could be under some static or dynamic router option.

Doing the same for handshake messages likely has effects on the state machine logic that many protocol implementations have.

**Comment by gammazero** [comment] 2018-03-05 18:06
It seems unnecessary to answer an invalid CALL with a CALL_ERROR.  The ERROR already contains the request ID, so the client is able to tell what the error is in response to.  Also, the client will need to look at the request ID in the error anyway to see which CALL is in error. In general, I would like to keep any optimization out of the error path.  It it takes a client a little longer to parse an error, fine, because it should not be the normal processing path.

Defaults for missing parameters may have unexpected consequences.  Without a clear and specific use case, explicit is better than implicit.

One thing I would like to see is a WAMP spec defined error URI for protocol violation.  Before a session is established, this would be returned in an ABORT when a message other than an expected HELLO is received.  URI could be something like: `wamp.exception.protocol_violation`

Also, the spec should be more specific about what the router should do when it receives a protocol violation.  Spec says `WAMP implementations MUST close sessions...`, but does not say if router is expected to send ABORT, or just close session/drop connection.

It would also be helpful to clarify what is a protocol violation (e.g. receiving ERROR from client that is not in response to INVOCATION) vs. an unexpected message that is not a protocol violation (e.g receiving a YIELD from a client for a CALL that has been canceled).

**Comment by gammazero** [comment] 2018-03-05 18:39
In my router implementation, any protocol violation before session is established results in ABORT with appropriate error URI and details.

Before a session is established:

- Invalid message (can't be json decoded) -> dropped, deserialize error logged
- Empty message or Any other message than HELLO -> ABORT `wamp.exception.protocol_violation`, close connection
- A short message (HELLO or not) -> ABORT, error depends on what is missing, close connection
- An invalid parameter in a message (HELLO or not). -> ABORT, depends on error: `wamp.error.no_such_realm`, `wamp.error.no_such_role`, etc. + error details, close connection
- HELLO with no roles -> ABORT `wamp.error.no_such_role` + "no client roles specified", close connection

After auth passed and session is established, the router is a little more relaxed.  We should decide if this is allowable in WAMP:

In my router implementation, after a session is authenticated and attached to a realm, the router does not kill the connection upon receiving an unexpected message. Instead it drops the message and logs the unhandled message, without an ERROR response to the client or closing the session.  My reasoning is: This is more interoperable with flawed client implementations. The client is presumed good since it was allowed (passed auth), and unexpected messages are harmless since they do not affect the state of the session in any way, so do not kill the session.

In my client library implementation, after joining a realm, if an invalid message code is received, then the message is dropped and logged.  If in invalid message is received as the response to a request, then an error is returned to the to the caller.  It is up to the client implementation to decide what to do with the error.  This would normally be to close the session, but this is a WAMP client library and maybe the application has reason to keep the session open (WAMP debugger?), so the library does not force a close.  That is up to the app implementation.

**Comment by oberstet** [comment] 2018-03-10 17:23
> We should decide if this is allowable in WAMP

The current spec text is pretty clear here: any protocol violation is fatal (=> drop connection). This is by design, and I would still vote for the same approach.

> This is more interoperable with flawed client implementations.

Ok, different approach. For me, this is an explicit non-goal: I don't want my implementations to encourage others not to fix issues;) and I don't want to open new attack surfaces in trying to continue talking to a broken peer.

> In my client library implementation

Currently, the Autobahn libraries are less strict than they could be on the client side too .. but I consider that bugs. If we find the time, the Autobahns will only get stricter on the client side too over time ..

**Comment by gammazero** [comment] 2018-03-11 07:30
I agree with your statements above, and I think it is important explicitly avoid new attack surfaces and error handling edge cases.

So, to summarize, if the peer cannot talk proper WAMP, then do not talk to the peer.

I will amend my implementation to be more strict.

**Comment by oberstet** [comment] 2018-03-11 10:01
>  it is important explicitly avoid new attack surfaces and error handling edge cases

exactly! maybe we should add such an explanation to the spec text as a reason why "fail fast, fail hard" is a good, because defensive approach. actually, that would really be good .. explaining why.

eg in as, trying to continue talking to a broken peer results in more states and cases to be considered down the line. if this is hitting a code location where the programmer with an implicit assumption "cannot be, because not allowed in protocol", bad stuff can happen.

this is of course making life harder for developers of peer _libraries_, but that can be solved differently (dev modes or sth). but it is a win on the security side I would argue.

**Comment by KSDaemon** [comment] 2018-03-12 15:46
Okay. Agreed. Lets be consistent. I'll also update all my implementations to send GOODBYE, "wamp.error.system_shutdown" in such cases.

**Comment by oberstet** [comment] 2018-03-12 18:05
@KSDaemon actually, thinking about what you wrote:

I am mostly arguing for not continue talking to a peer that violates the protocols (in a significant way) - I am not actually caring much about how to end a connection to such a peer. I think crossbar fails a connection hard (drops the TCP connection), which is of course least further risk, but also quite unhelpful.

the problem is: with a router initiated GOODBYE, the router would normally wait - and parse etc - a client response (GOODBYE) -- and that should not happen. it is completely fine for the router to send out a GOODBYE with error eg `wamp.error.protocol_violation` and details in reason string. but it must not wait - _nor process_ - anything from the point onwards it detected the protocol violation.

so it is: detect protocol violation => mark as "ignore any further input", send GOODBYE, push out bytes and close TCP.

that would be secure and helpful way of handling protocol violations ..

**Closed** 2018-03-16 11:37 UTC
Labels: Basic Profile, Bug
